tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "ccache"
brew "cmake"
brew "eza"
brew "fd"
brew "fish"
brew "fmt"
brew "git"
brew "gitui"
brew "gtop"
brew "llvm"
brew "mas"
brew "neovim"
brew "ninja"
brew "peco"
brew "ripgrep"
brew "sheldon"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "doxygen"
brew "graphviz"
brew "jq"
brew "gnu-sed"
cask "ngrok/ngrok/ngrok"
cask "font-fira-code-nerd-font"
cask "keycastr"
cask "raycast"
cask "wezterm"
mas "LINE", id: 539883307
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
